version: "3.3"
services:
    backend:
        build: .
        image: registry.gitlab.com/witpakul/witpakul-ii-backend:latest
        container_name: WitPaKul_Backend
        volumes:
           - ./data:/app/data/

networks:
    default:
        external:
            name: witpakul_network 
